ALTER TABLE DSRTable ALTER  COLUMN  plannedtask varchar(1000);
ALTER TABLE DSRTable ALTER  COLUMN  accomplishedtask varchar(1000);
ALTER TABLE DSRTable ALTER  COLUMN  remarks varchar(1000);

ALTER TABLE KTTable ALTER COLUMN title varchar(1000);
ALTER TABLE KTTable ALTER COLUMN trainers varchar(1000);
ALTER TABLE KTTable ALTER COLUMN attendees varchar(1000);
ALTER TABLE KTTable ALTER COLUMN remarks varchar(1000);
ALTER TABLE KTTable ALTER COLUMN feedback varchar(1000);

ALTER TABLE KTTable ADD CONSTRAINT PK_TRAINING_ID PRIMARY KEY CLUSTERED (tri_id); 

ALTER TABLE LEAVEDETAILS ADD gKey int identity(1,1);

ALTER TABLE LEAVEPLANSINFO ADD gKey int identity(1,1);

ALTER TABLE PERMISSIONDETAILS ADD gKey int identity(1,1);

truncate table ISDQAReports..REMAINDERS;
ALTER TABLE ISDQAReports..REMAINDERS ADD gkey int IDENTITY(1,1) NOT NULL PRIMARY KEY;
ALTER TABLE ISDQAReports..REMAINDERS ADD USER_ID varchar(50) NOT NULL;